### ISSUE TITLE
broken conflict of interest link on guide for editors

### ISSUE THREAD

**Issue by NickleDave** [pyOpenSci/contributing-guide#80]
This link in the editors guide to the COI language is broken:
https://www.pyopensci.org/contributing-guide/open-source-software-submissions/editors-guide.html

This is the link in the .md here:
https://github.com/pyOpenSci/contributing-guide/blame/master/open-source-software-submissions/editors-guide.md#L58
```* No [conflicts of interest](peer_review_proc#conflict-of-interest)```

Presumably we want it to go to:
https://www.pyopensci.org/contributing-guide/open-source-software-peer-review/policies-and-guidelines.html#conflict-of-interest

**Comment by lwasser** [comment]
@NickleDave i just fixed this. I'll work on the other COI related issue next week. i think that one deserves a bit more text and such in that section! i also think we can make things look nicer with breakout boxes and such given we are in sphinx world here!

**Comment by NickleDave** [comment]
🤔 I still get a 404 when I click on this link?
https://www.pyopensci.org/contributing-guide/open-source-software-submissions/peer_review_proc#conflict-of-interest

I'm clicking here
![Screen Shot 2021-05-22 at 10 14 41 AM](https://user-images.githubusercontent.com/11934090/119229598-c416b900-bae6-11eb-93f8-79f9dfeda992.png)

**Comment by lwasser** [comment]
hey @NickleDave thank you.  i  had the PR opened  but only merged it this morning as i ended up doing a bunch of other edits. there are still a lot of   issues with that page  but can  you have a look again please? i've redone the page and started a revisit of the content - merged this am.

**Comment by lwasser** [comment]
here is the link - https://www.pyopensci.org/contributing-guide/open-source-software-submissions/editors-guide.html#criteria-for-choosing-reviewers just in case i've reopened  this issue until you check it again to ensure i'm not missing something.

**Comment by NickleDave** [comment]
I was able to click on it now and have that link resolve properly to https://www.pyopensci.org/contributing-guide/open-source-software-peer-review/policies-and-guidelines.html#conflict-of-interest

so I think this is fixed
